DROP TABLE IF EXISTS Q3 CASCADE;
CREATE TABLE Q3 (
    Q3_ORDERKEY        BIGINT,
    Q3_ORDERDATE       DATE,
    Q3_SHIPPRIORITY    INTEGER,
    Q3_EXTENDEDPRICE     DECIMAL,
    Q3_DISCOUNT          DECIMAL
);

DROP TABLE IF EXISTS Q3_C_O CASCADE;
CREATE TABLE Q3_C_O (
    Q3_C_O_ORDERKEY BIGINT,
    Q3_C_O_ORDERDATE       DATE,
    Q3_C_O_SHIPPRIORITY    INTEGER
);

DROP TABLE IF EXISTS Q3_O CASCADE;
CREATE TABLE Q3_O (
    Q3_O_CUSTKEY         BIGINT,
    Q3_O_ORDERKEY        BIGINT,
    Q3_O_ORDERDATE       DATE,
    Q3_O_SHIPPRIORITY    INTEGER
);

DROP TABLE IF EXISTS Q3_C CASCADE;
CREATE TABLE Q3_C (
    Q3_C_CUSTKEY         BIGINT
);

DROP TABLE IF EXISTS Q3_L CASCADE;
CREATE TABLE Q3_L (
    Q3_L_ORDERKEY        BIGINT,
    Q3_L_EXTENDEDPRICE     DECIMAL,
    Q3_L_DISCOUNT          DECIMAL
);

DROP TABLE IF EXISTS Q3_O_L CASCADE;
CREATE TABLE Q3_O_L (
    Q3_O_L_CUSTKEY         BIGINT, 
    Q3_O_L_ORDERKEY        BIGINT,
    Q3_O_L_ORDERDATE       DATE,
    Q3_O_L_SHIPPRIORITY    INTEGER,
    Q3_O_L_EXTENDEDPRICE     DECIMAL,
    Q3_O_L_DISCOUNT          DECIMAL
);


