DROP TABLE IF EXISTS I12_L CASCADE;
DROP TABLE IF EXISTS I12_O CASCADE;

CREATE TABLE I12_L (
	I12_L_ORDERKEY	BIGINT,
	I12_L_SHIPMODE	CHAR(10)
);

CREATE TABLE I12_O (
	I12_O_ORDERKEY		BIGINT,
	I12_O_ORDERPRIORITY	CHAR(15)
);



