DROP TABLE IF EXISTS I19_L CASCADE;
DROP TABLE IF EXISTS I19_P CASCADE;

CREATE TABLE I19_L (
	I19_L_PARTKEY		BIGINT,
	I19_l_linenumber 	INTEGER,
	I19_l_extendedprice	DECIMAL,
	I19_l_discount		DECIMAL
);

CREATE TABLE I19_P (
	I19_p_partkey		BIGINT
);



